### ISSUE TITLE
System Crash

### ISSUE THREAD

**Issue by wesferr** [Harpia-development/device_motorola_harpia#2]
My phone system are crashing constantly, follow the fatla error code:
`05-15 14:14:52.942  3834  3834 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-15 14:14:52.942  3834  3834 F DEBUG   : Build fingerprint: 'motorola/harpia/harpia:7.1.1/NPIS26.48-36-5/12:user/release-keys'
05-15 14:14:52.942  3834  3834 F DEBUG   : Revision: '0'
05-15 14:14:52.942  3834  3834 F DEBUG   : ABI: 'arm'
05-15 14:14:52.942  3834  3834 F DEBUG   : pid: 20978, tid: 20978, name: surfaceflinger  >>> /system/bin/surfaceflinger <<<
05-15 14:14:52.942  3834  3834 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
05-15 14:14:52.942  3834  3834 F DEBUG   : Cause: null pointer dereference
05-15 14:14:52.942  3834  3834 F DEBUG   :     r0  a9c55000  r1  00000000  r2  0000011e  r3  0000035f
05-15 14:14:52.942  3834  3834 F DEBUG   :     r4  aad5b19c  r5  a8339370  r6  00000000  r7  00000002
05-15 14:14:52.942  3834  3834 F DEBUG   :     r8  bec312cb  r9  00000000  r10 bec313d8  r11 00000000
05-15 14:14:52.943  3834  3834 F DEBUG   :     ip  abf48fe4  sp  bec31230  lr  a9ba2dd1  pc  00000000
05-15 14:14:52.996  3834  3834 F DEBUG   : 
05-15 14:14:52.996  3834  3834 F DEBUG   : backtrace:
05-15 14:14:52.997  3834  3834 F DEBUG   :     #00 pc 00000000  <unknown>
05-15 14:14:52.997  3834  3834 F DEBUG   :     #01 pc 00009dcf  /system/vendor/lib/libhwc2on1adapter.so (_ZN7android14HWC2On1Adapter9layerHookIMNS0_5LayerEFN4HWC25ErrorEiiEXadL_ZNS2_17setCursorPositionEiiEEJiiEEEiP11hwc2_deviceyyDpT1_+86)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #02 pc 0000ae0d  /system/vendor/lib/hw/android.hardware.graphics.composer@2.1-impl.so (android::hardware::graphics::composer::V2_1::hal::ComposerCommandEngine::executeCommand(android::hardware::graphics::composer::V2_1::IComposerClient::Command, unsigned short)+1012)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #03 pc 0000a00b  /system/vendor/lib/hw/android.hardware.graphics.composer@2.1-impl.so (android::hardware::graphics::composer::V2_1::hal::ComposerCommandEngine::execute(unsigned int, android::hardware::hidl_vec<android::hardware::hidl_handle> const&, bool*, unsigned int*, android::hardware::hidl_vec<android::hardware::hidl_handle>*)+90)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #04 pc 00008141  /system/vendor/lib/hw/android.hardware.graphics.composer@2.1-impl.so (android::hardware::graphics::composer::V2_1::hal::detail::ComposerClientImpl<android::hardware::graphics::composer::V2_1::IComposerClient, android::hardware::graphics::composer::V2_1::hal::ComposerHal>::executeCommands(unsigned int, android::hardware::hidl_vec<android::hardware::hidl_handle> const&, std::__1::function<void (android::hardware::graphics::composer::V2_1::Error, bool, unsigned int, android::hardware::hid
05-15 14:14:52.997  3834  3834 F DEBUG   :     #05 pc 0002e41d  /system/lib/android.hardware.graphics.composer@2.1.so (android::hardware::graphics::composer::V2_1::BsComposerClient::executeCommands(unsigned int, android::hardware::hidl_vec<android::hardware::hidl_handle> const&, std::__1::function<void (android::hardware::graphics::composer::V2_1::Error, bool, unsigned int, android::hardware::hidl_vec<android::hardware::hidl_handle> const&)>)+120)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #06 pc 00046793  /system/lib/libsurfaceflinger.so (android::Hwc2::impl::Composer::execute()+1286)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #07 pc 00047d6f  /system/lib/libsurfaceflinger.so (android::Hwc2::impl::Composer::presentOrValidateDisplay(unsigned long long, unsigned int*, unsigned int*, int*, unsigned int*)+136)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #08 pc 0004e6ed  /system/lib/libsurfaceflinger.so (HWC2::Display::presentOrValidate(unsigned int*, unsigned int*, android::sp<android::Fence>*, unsigned int*)+60)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #09 pc 00052135  /system/lib/libsurfaceflinger.so (android::HWComposer::prepare(android::DisplayDevice&)+276)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #10 pc 00044a0b  /system/lib/libsurfaceflinger.so (android::DisplayDevice::prepareFrame(android::HWComposer&)+10)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #11 pc 00073425  /system/lib/libsurfaceflinger.so (android::SurfaceFlinger::handleMessageRefresh()+1252)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #12 pc 000722b9  /system/lib/libsurfaceflinger.so (android::SurfaceFlinger::onMessageReceived(int)+196)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #13 pc 0000f0db  /system/lib/libutils.so (android::Looper::pollInner(int)+286)
05-15 14:14:52.997  3834  3834 F DEBUG   :     #14 pc 0000ef3f  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+26)
05-15 14:14:52.999  3834  3834 F DEBUG   :     #15 pc 00066c13  /system/lib/libsurfaceflinger.so (android::impl::MessageQueue::waitMessage()+62)
05-15 14:14:52.999  3834  3834 F DEBUG   :     #16 pc 00071ae1  /system/lib/libsurfaceflinger.so (android::SurfaceFlinger::run()+8)
05-15 14:14:52.999  3834  3834 F DEBUG   :     #17 pc 0000280b  /system/bin/surfaceflinger (main+642)
05-15 14:14:52.999  3834  3834 F DEBUG   :     #18 pc 00088a91  /system/lib/libc.so (__libc_init+48)
05-15 14:14:52.999  3834  3834 F DEBUG   :     #19 pc 00002547  /system/bin/surfaceflinger (_start_main+38)
05-15 14:14:52.999  3834  3834 F DEBUG   :     #20 pc 0000031e  <anonymous:ac51f000>`

**Comment by Akianonymus** [comment]
need a full log

**Comment by wesferr** [comment]
how can i get this?

**Comment by Akianonymus** [comment]
the same you took the above log 

just don't trim the log, give me all of it

**Comment by FacuM** [comment]
No answer from the OP, closing. Feel free to open it back if needed.
